[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
hex = "0.4.3"
md5 = "0.7.0"
openssl = "0.10.64"
serde = "1.0.198"
